import type { CityKey } from "@/lib/location-data";

export interface LocationSeoContent {
  heroImageAlt: string;
  localPatientHeading: string;
  localPatientInfo: string;
  serviceLinksIntro: string;
  servicePageKeys: string[];
}

export const LOCATION_SEO: Record<CityKey, LocationSeoContent> = {
  bhubaneswar: {
    heroImageAlt: "Dental implant consultation in Bhubaneswar at CARE Hospital",
    localPatientHeading: "Planning implant care within Bhubaneswar",
    localPatientInfo: "Patients in Bhubaneswar can attend their examination, indicated imaging, implant procedure and restorative appointments at CARE Hospital in Chandrasekharpur. The number and spacing of visits depend on whether the case involves one tooth, several teeth, bone preparation or full-arch rehabilitation.",
    serviceLinksIntro: "Compare the most relevant implant options before arranging a dental implant consultation in Bhubaneswar. The appropriate procedure is confirmed after examination and imaging.",
    servicePageKeys: ["single", "multiple", "allon", "fullmouth", "cost"],
  },
  cuttack: {
    heroImageAlt: "Online dental implant consultation for a patient from Cuttack before Bhubaneswar treatment",
    localPatientHeading: "Coordinating treatment from Cuttack",
    localPatientInfo: "For Cuttack patients, the short journey to Chandrasekharpur can make separate assessment and treatment visits practical. Existing X-rays may be shared first, but implant suitability, bone condition and the final plan are confirmed only during an in-person examination in Bhubaneswar.",
    serviceLinksIntro: "Cuttack dental implant enquiries commonly involve a single missing tooth, several missing teeth or a comparison with bridges and dentures. These guides explain the choices before travel to Bhubaneswar.",
    servicePageKeys: ["single", "multiple", "compare", "cost"],
  },
  puri: {
    heroImageAlt: "Dental implant planning consultation for a patient travelling from Puri to Bhubaneswar",
    localPatientHeading: "Preparing for a visit from Puri",
    localPatientInfo: "Patients travelling from Puri can use an online consultation to discuss symptoms, medical history and any available dental records before choosing a travel date. Clinical examination and all implant treatment take place at CARE Hospital, Bhubaneswar; additional visits depend on healing and the restoration planned.",
    serviceLinksIntro: "Patients from Puri can review single-tooth, immediate-placement and full-mouth options, plus the factors that affect cost, before an in-person assessment in Bhubaneswar.",
    servicePageKeys: ["single", "immediate", "fullmouth", "cost"],
  },
  berhampur: {
    heroImageAlt: "Remote dental implant consultation for a Berhampur patient planning treatment in Bhubaneswar",
    localPatientHeading: "Planning care from Berhampur and Ganjam",
    localPatientInfo: "A dental implant consultation for Berhampur patients can begin online so the team can review the reason for tooth loss and available reports. Because treatment is provided only in Bhubaneswar, patients should wait for a confirmed appointment and visit plan before arranging travel from Ganjam.",
    serviceLinksIntro: "For patients travelling from Berhampur, these guides cover common needs including one missing tooth, full-arch replacement, bone grafting and treatment-cost planning.",
    servicePageKeys: ["single", "allon", "bone", "cost"],
  },
  sambalpur: {
    heroImageAlt: "Dental implant video consultation for a Sambalpur patient before hospital treatment in Bhubaneswar",
    localPatientHeading: "Reducing unnecessary trips from Sambalpur",
    localPatientInfo: "Sambalpur patients can first share their concerns and existing scans online. The team can then coordinate the examination and indicated imaging in Bhubaneswar, while explaining which later stages require a return visit. Online review supports planning but does not replace the clinical assessment.",
    serviceLinksIntro: "Patients from Sambalpur who have extensive tooth loss may find the full-mouth, All-on-4 or All-on-6, bone-grafting and cost guides especially useful before travelling.",
    servicePageKeys: ["fullmouth", "allon", "bone", "cost"],
  },
  rourkela: {
    heroImageAlt: "Dental implant consultation for a Rourkela patient arranging treatment at CARE Hospital Bhubaneswar",
    localPatientHeading: "Organising multi-stage care from Rourkela",
    localPatientInfo: "Dental implant treatment for patients from Rourkela may involve more than one Bhubaneswar visit for assessment, surgery, review and the final restoration. An online discussion can help sequence those visits around available rail, road or air travel without promising that treatment can be completed in one trip.",
    serviceLinksIntro: "Rourkela patients can use these guides to compare full-mouth rehabilitation, fixed full-arch options, preparatory grafting and overall treatment-cost factors.",
    servicePageKeys: ["fullmouth", "allon", "bone", "cost"],
  },
  balasore: {
    heroImageAlt: "Online dental implant consultation for a Balasore patient travelling to Bhubaneswar",
    localPatientHeading: "Coordinating appointments from Balasore",
    localPatientInfo: "Patients from Balasore or Baleswar can begin by sharing available dental records and discussing the likely sequence of care. Examination, imaging when indicated, implant placement and restorative treatment are carried out in Bhubaneswar, with appointment timing confirmed before travel.",
    serviceLinksIntro: "Balasore patients can explore single-tooth and multiple-tooth replacement, immediate placement criteria and cost factors before arranging their Bhubaneswar assessment.",
    servicePageKeys: ["single", "multiple", "immediate", "cost"],
  },
  baripada: {
    heroImageAlt: "Dental implant consultation for a Baripada patient planning care in Bhubaneswar",
    localPatientHeading: "Dental implant planning from Mayurbhanj",
    localPatientInfo: "For Baripada and Mayurbhanj patients, an initial online conversation can clarify which records to bring and how appointments may be grouped. It cannot confirm implant suitability or final cost; those decisions follow examination and any required imaging at CARE Hospital, Bhubaneswar.",
    serviceLinksIntro: "These guides help Baripada patients understand single-tooth replacement, multiple implants, bone preparation and treatment-cost considerations before travel.",
    servicePageKeys: ["single", "multiple", "bone", "cost"],
  },
  angul: {
    heroImageAlt: "Dental implant consultation for an Angul patient before travelling to CARE Hospital Bhubaneswar",
    localPatientHeading: "Planning a Bhubaneswar visit from Angul",
    localPatientInfo: "Angul patients can request a preliminary online review before travelling via Dhenkanal. The in-person visit is used to examine the mouth, review bone and gum health, and decide whether implant placement can proceed or requires preparatory care. Treatment is provided in Bhubaneswar, not at an Angul branch.",
    serviceLinksIntro: "For Angul dental implant enquiries, these guides explain single-tooth treatment, immediate-placement criteria, bone grafting and the factors used to prepare a cost estimate.",
    servicePageKeys: ["single", "immediate", "bone", "cost"],
  },
  jharsuguda: {
    heroImageAlt: "Remote dental implant consultation for a Jharsuguda patient arranging Bhubaneswar treatment",
    localPatientHeading: "Sequencing treatment from Jharsuguda",
    localPatientInfo: "Patients from Jharsuguda, Brajrajnagar and Belpahar can discuss their needs online before making a longer trip. The team can outline likely stages and coordinate appointments, but examination in Bhubaneswar is required before confirming implant number, grafting needs, timing or final cost.",
    serviceLinksIntro: "Jharsuguda patients planning a longer journey can compare full-mouth and full-arch care, guided implant planning, bone grafting and cost considerations here.",
    servicePageKeys: ["fullmouth", "allon", "bone", "cost"],
  },
  jayadev_vihar: {
    heroImageAlt: "Dental implant consultation for Jayadev Vihar patients at CARE Hospital Chandrasekharpur",
    localPatientHeading: "Planning implant care for Jayadev Vihar residents",
    localPatientInfo: "Jayadev Vihar residents can attend initial examinations, 3D CBCT imaging, surgical implant placement, and crown restorations at CARE Hospital in nearby Chandrasekharpur (~4 km away). Consultations and pre-evaluations can be coordinated online or via WhatsApp.",
    serviceLinksIntro: "Review relevant dental implant procedures before scheduling your consultation in Chandrasekharpur. Procedure selection is confirmed following clinical examination and CBCT imaging.",
    servicePageKeys: ["single", "multiple", "allon", "immediate", "cost"],
  },
  saheed_nagar: {
    heroImageAlt: "Dental implant consultation for Saheed Nagar patients at CARE Hospital Chandrasekharpur",
    localPatientHeading: "Coordinating implant treatment from Saheed Nagar",
    localPatientInfo: "For Saheed Nagar residents, traveling along Janpath to Chandrasekharpur takes under 18 minutes. Clinical examination, 3D CBCT scanning, and surgical placement take place at CARE Hospital.",
    serviceLinksIntro: "Explore options for replacing one tooth, several teeth, or full mouth restorations before arranging your appointment.",
    servicePageKeys: ["single", "multiple", "allon", "cost", "compare"],
  },
  nayapalli: {
    heroImageAlt: "Dental implant treatment guidance for Nayapalli residents",
    localPatientHeading: "Implant care workflow for Nayapalli patients",
    localPatientInfo: "Nayapalli patients can reach CARE Hospital via Jaydev Vihar Flyover in ~15 minutes for 3D CBCT scans, guided flapless implant surgery, and crown fitting.",
    serviceLinksIntro: "Learn about flapless guided placement, single implants, and full mouth rehabilitations available for Nayapalli residents.",
    servicePageKeys: ["single", "immediate", "allon", "bone", "cost"],
  },
  chandrasekharpur: {
    heroImageAlt: "Dental implant treatment center at CARE Hospital Chandrasekharpur Bhubaneswar",
    localPatientHeading: "Direct local surgical care in Chandrasekharpur",
    localPatientInfo: "Chandrasekharpur residents have direct local access to CARE Hospital on Prachi Enclave Road for on-site 3D CBCT diagnostics, expert MDS implantology, and sterile surgical suites.",
    serviceLinksIntro: "Explore our full range of dental implant services available directly in Chandrasekharpur.",
    servicePageKeys: ["single", "multiple", "allon", "fullmouth", "immediate", "bone", "cost"],
  },
  patia: {
    heroImageAlt: "Dental implant consultation for Patia and KIIT area residents",
    localPatientHeading: "Convenient implant care for Patia residents",
    localPatientInfo: "Located just 3 km down Nandankanan Road, Patia and Infocity residents can complete 3D CBCT imaging and guided surgery at CARE Hospital Chandrasekharpur.",
    serviceLinksIntro: "Compare single tooth, immediate load, and full arch implant options for Patia patients.",
    servicePageKeys: ["single", "immediate", "allon", "cost"],
  },
  sailashree_vihar: {
    heroImageAlt: "Dental implant guidance for Sailashree Vihar residents",
    localPatientHeading: "Implant care just 5 minutes from Sailashree Vihar",
    localPatientInfo: "Sailashree Vihar residents benefit from immediate neighborhood proximity to CARE Hospital in Chandrasekharpur (~2 km away).",
    serviceLinksIntro: "Review dental implant solutions and pricing factors for Sailashree Vihar patients.",
    servicePageKeys: ["single", "multiple", "immediate", "cost"],
  },
  niladri_vihar: {
    heroImageAlt: "Dental implant consultation for Niladri Vihar residents",
    localPatientHeading: "Local implant access for Niladri Vihar",
    localPatientInfo: "Niladri Vihar residents can reach CARE Hospital on Prachi Enclave Road in under 5 minutes for 3D CBCT diagnostics and flapless implant surgery.",
    serviceLinksIntro: "Explore tooth replacement choices and cost guides for Niladri Vihar residents.",
    servicePageKeys: ["single", "multiple", "cost", "compare"],
  },
  kharavela_nagar: {
    heroImageAlt: "Dental implant consultation for Kharavela Nagar residents",
    localPatientHeading: "Implant treatment for Kharavela Nagar & Unit-3",
    localPatientInfo: "Kharavela Nagar residents travel ~20 minutes up Janpath to CARE Hospital Chandrasekharpur for 3D CBCT imaging and guided surgical placement.",
    serviceLinksIntro: "Compare single tooth implants, multi-implant bridges, and full mouth rehabilitations.",
    servicePageKeys: ["single", "multiple", "allon", "fullmouth", "cost"],
  },
  acharya_vihar: {
    heroImageAlt: "Dental implant consultation for Acharya Vihar residents",
    localPatientHeading: "Implant care for Acharya Vihar & Utkal University area",
    localPatientInfo: "Acharya Vihar residents reach CARE Hospital Chandrasekharpur in ~12 minutes via Nandankanan Road for expert implant placement and zirconia crown fitting.",
    serviceLinksIntro: "Learn about single tooth, immediate placement, and cost guidelines.",
    servicePageKeys: ["single", "immediate", "bone", "cost"],
  },
  satya_nagar: {
    heroImageAlt: "Dental implant consultation for Satya Nagar residents",
    localPatientHeading: "Implant treatment for Satya Nagar patients",
    localPatientInfo: "Satya Nagar residents travel ~18 minutes via Janpath to CARE Hospital Chandrasekharpur for 3D CBCT diagnostics and Maxillofacial implantology.",
    serviceLinksIntro: "Explore options for replacing missing teeth and understanding treatment costs.",
    servicePageKeys: ["single", "multiple", "allon", "cost"],
  },
  forest_park: {
    heroImageAlt: "Dental implant consultation for Forest Park residents",
    localPatientHeading: "Implant care for Forest Park & Bapuji Nagar",
    localPatientInfo: "Forest Park residents travel ~22 minutes via Jaydev Vihar Flyover to CARE Hospital Chandrasekharpur for guided flapless surgery.",
    serviceLinksIntro: "Compare single tooth, full-arch, and cost guides before your consultation.",
    servicePageKeys: ["single", "allon", "fullmouth", "cost"],
  },
  gajapati_nagar: {
    heroImageAlt: "Dental implant consultation for Gajapati Nagar residents",
    localPatientHeading: "Implant treatment for Gajapati Nagar patients",
    localPatientInfo: "Gajapati Nagar residents travel ~10 minutes via Sainik School Road to CARE Hospital Chandrasekharpur for 3D CBCT scanning and surgery.",
    serviceLinksIntro: "Explore single tooth and multi-implant options tailored for Gajapati Nagar patients.",
    servicePageKeys: ["single", "multiple", "immediate", "cost"],
  },
  dumduma: {
    heroImageAlt: "Dental implant consultation for Dumduma residents",
    localPatientHeading: "Implant care for Dumduma & AIIMS area residents",
    localPatientInfo: "Dumduma residents travel ~30 minutes via NH16 Flyovers to CARE Hospital Chandrasekharpur for specialized implantology.",
    serviceLinksIntro: "Learn about single tooth, full arch All-on-4, and bone grafting options.",
    servicePageKeys: ["single", "allon", "fullmouth", "bone", "cost"],
  },
  pokhariput: {
    heroImageAlt: "Dental implant consultation for Pokhariput residents",
    localPatientHeading: "Implant care for Pokhariput & Old Town area",
    localPatientInfo: "Pokhariput residents travel ~25 minutes via Aerodrome Road / Jaydev Vihar to CARE Hospital Chandrasekharpur for 3D CBCT scanning and implant placement.",
    serviceLinksIntro: "Explore single tooth, multiple implant, and cost guides.",
    servicePageKeys: ["single", "multiple", "allon", "cost"],
  },
  kalinga_nagar: {
    heroImageAlt: "Dental implant consultation for Kalinga Nagar residents",
    localPatientHeading: "Implant care for Kalinga Nagar & Ghatikia residents",
    localPatientInfo: "Kalinga Nagar residents travel ~28 minutes via Khandagiri and Jaydev Vihar Flyovers to CARE Hospital Chandrasekharpur for expert implant care.",
    serviceLinksIntro: "Compare full arch restorations, single implants, and bone grafting options.",
    servicePageKeys: ["single", "allon", "fullmouth", "bone", "cost"],
  },
  patrapada: {
    heroImageAlt: "Dental implant consultation for Patrapada residents",
    localPatientHeading: "Implant care for Patrapada residents",
    localPatientInfo: "Patrapada residents travel ~30 minutes northbound via NH16 Highway to CARE Hospital Chandrasekharpur for 3D CBCT imaging and guided surgery.",
    serviceLinksIntro: "Explore single tooth, full arch, and cost options.",
    servicePageKeys: ["single", "allon", "fullmouth", "cost"],
  },
  sundarpur: {
    heroImageAlt: "Dental implant consultation for Sundarpur residents",
    localPatientHeading: "Implant care for Sundarpur & Silicon College area",
    localPatientInfo: "Sundarpur residents travel ~12 minutes via Patia Square to CARE Hospital Chandrasekharpur for 3D CBCT scans and flapless guided surgery.",
    serviceLinksIntro: "Review single tooth, immediate placement, and cost guidelines.",
    servicePageKeys: ["single", "immediate", "bone", "cost"],
  },
};