/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllOn4AllOn6OdishaRouteImport } from './routes/all-on-4-all-on-6-odisha'
import { Route as BoneGraftingForDentalImplantsRouteImport } from './routes/bone-grafting-for-dental-implants'
import { Route as DentalImplantCostBhubaneswarRouteImport } from './routes/dental-implant-cost-bhubaneswar'
import { Route as DentalImplantCostOdishaRouteImport } from './routes/dental-implant-cost-odisha'
import { Route as DentalImplantMaintenanceFailureRouteImport } from './routes/dental-implant-maintenance-failure'
import { Route as DentalImplantSecondOpinionRouteImport } from './routes/dental-implant-second-opinion'
import { Route as DentalImplantsAcharyaViharRouteImport } from './routes/dental-implants-acharya-vihar'
import { Route as DentalImplantsAngulRouteImport } from './routes/dental-implants-angul'
import { Route as DentalImplantsBalasoreRouteImport } from './routes/dental-implants-balasore'
import { Route as DentalImplantsBaripadaRouteImport } from './routes/dental-implants-baripada'
import { Route as DentalImplantsBerhampurRouteImport } from './routes/dental-implants-berhampur'
import { Route as DentalImplantsBhubaneswarRouteImport } from './routes/dental-implants-bhubaneswar'
import { Route as DentalImplantsChandrasekharpurRouteImport } from './routes/dental-implants-chandrasekharpur'
import { Route as DentalImplantsCuttackRouteImport } from './routes/dental-implants-cuttack'
import { Route as DentalImplantsDumdumaRouteImport } from './routes/dental-implants-dumduma'
import { Route as DentalImplantsForestParkRouteImport } from './routes/dental-implants-forest-park'
import { Route as DentalImplantsGajapatiNagarRouteImport } from './routes/dental-implants-gajapati-nagar'
import { Route as DentalImplantsJayadevViharRouteImport } from './routes/dental-implants-jayadev-vihar'
import { Route as DentalImplantsJharsugudaRouteImport } from './routes/dental-implants-jharsuguda'
import { Route as DentalImplantsKalingaNagarRouteImport } from './routes/dental-implants-kalinga-nagar'
import { Route as DentalImplantsKharavelaNagarRouteImport } from './routes/dental-implants-kharavela-nagar'
import { Route as DentalImplantsNayapalliRouteImport } from './routes/dental-implants-nayapalli'
import { Route as DentalImplantsNiladriViharRouteImport } from './routes/dental-implants-niladri-vihar'
import { Route as DentalImplantsPatiaRouteImport } from './routes/dental-implants-patia'
import { Route as DentalImplantsPatrapadaRouteImport } from './routes/dental-implants-patrapada'
import { Route as DentalImplantsPokhariputRouteImport } from './routes/dental-implants-pokhariput'
import { Route as DentalImplantsPuriRouteImport } from './routes/dental-implants-puri'
import { Route as DentalImplantsRourkelaRouteImport } from './routes/dental-implants-rourkela'
import { Route as DentalImplantsSaheedNagarRouteImport } from './routes/dental-implants-saheed-nagar'
import { Route as DentalImplantsSailashreeViharRouteImport } from './routes/dental-implants-sailashree-vihar'
import { Route as DentalImplantsSambalpurRouteImport } from './routes/dental-implants-sambalpur'
import { Route as DentalImplantsSatyaNagarRouteImport } from './routes/dental-implants-satya-nagar'
import { Route as DentalImplantsSundarpurRouteImport } from './routes/dental-implants-sundarpur'
import { Route as DrSauvikSinghaRouteImport } from './routes/dr-sauvik-singha'
import { Route as FlaplessGuidedDentalImplantsRouteImport } from './routes/flapless-guided-dental-implants'
import { Route as FullMouthDentalImplantsRouteImport } from './routes/full-mouth-dental-implants'
import { Route as ImmediateDentalImplantsRouteImport } from './routes/immediate-dental-implants'
import { Route as ImplantsVsBridgeVsDentureRouteImport } from './routes/implants-vs-bridge-vs-denture'
import { Route as MultipleDentalImplantsRouteImport } from './routes/multiple-dental-implants'
import { Route as SingleToothDentalImplantRouteImport } from './routes/single-tooth-dental-implant'
import { Route as SinusLiftDentalImplantsRouteImport } from './routes/sinus-lift-dental-implants'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ZirconiaCrownsSmileDesignRouteImport } from './routes/zirconia-crowns-smile-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllOn4AllOn6OdishaRoute = AllOn4AllOn6OdishaRouteImport.update({
  id: '/all-on-4-all-on-6-odisha',
  path: '/all-on-4-all-on-6-odisha',
  getParentRoute: () => rootRouteImport,
} as any)
const BoneGraftingForDentalImplantsRoute =
  BoneGraftingForDentalImplantsRouteImport.update({
    id: '/bone-grafting-for-dental-implants',
    path: '/bone-grafting-for-dental-implants',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantCostBhubaneswarRoute =
  DentalImplantCostBhubaneswarRouteImport.update({
    id: '/dental-implant-cost-bhubaneswar',
    path: '/dental-implant-cost-bhubaneswar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantCostOdishaRoute = DentalImplantCostOdishaRouteImport.update({
  id: '/dental-implant-cost-odisha',
  path: '/dental-implant-cost-odisha',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantMaintenanceFailureRoute =
  DentalImplantMaintenanceFailureRouteImport.update({
    id: '/dental-implant-maintenance-failure',
    path: '/dental-implant-maintenance-failure',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantSecondOpinionRoute =
  DentalImplantSecondOpinionRouteImport.update({
    id: '/dental-implant-second-opinion',
    path: '/dental-implant-second-opinion',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsAcharyaViharRoute =
  DentalImplantsAcharyaViharRouteImport.update({
    id: '/dental-implants-acharya-vihar',
    path: '/dental-implants-acharya-vihar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsAngulRoute = DentalImplantsAngulRouteImport.update({
  id: '/dental-implants-angul',
  path: '/dental-implants-angul',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBalasoreRoute = DentalImplantsBalasoreRouteImport.update({
  id: '/dental-implants-balasore',
  path: '/dental-implants-balasore',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBaripadaRoute = DentalImplantsBaripadaRouteImport.update({
  id: '/dental-implants-baripada',
  path: '/dental-implants-baripada',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBerhampurRoute = DentalImplantsBerhampurRouteImport.update({
  id: '/dental-implants-berhampur',
  path: '/dental-implants-berhampur',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBhubaneswarRoute =
  DentalImplantsBhubaneswarRouteImport.update({
    id: '/dental-implants-bhubaneswar',
    path: '/dental-implants-bhubaneswar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsChandrasekharpurRoute =
  DentalImplantsChandrasekharpurRouteImport.update({
    id: '/dental-implants-chandrasekharpur',
    path: '/dental-implants-chandrasekharpur',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsCuttackRoute = DentalImplantsCuttackRouteImport.update({
  id: '/dental-implants-cuttack',
  path: '/dental-implants-cuttack',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsDumdumaRoute = DentalImplantsDumdumaRouteImport.update({
  id: '/dental-implants-dumduma',
  path: '/dental-implants-dumduma',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsForestParkRoute =
  DentalImplantsForestParkRouteImport.update({
    id: '/dental-implants-forest-park',
    path: '/dental-implants-forest-park',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsGajapatiNagarRoute =
  DentalImplantsGajapatiNagarRouteImport.update({
    id: '/dental-implants-gajapati-nagar',
    path: '/dental-implants-gajapati-nagar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsJayadevViharRoute =
  DentalImplantsJayadevViharRouteImport.update({
    id: '/dental-implants-jayadev-vihar',
    path: '/dental-implants-jayadev-vihar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsJharsugudaRoute =
  DentalImplantsJharsugudaRouteImport.update({
    id: '/dental-implants-jharsuguda',
    path: '/dental-implants-jharsuguda',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsKalingaNagarRoute =
  DentalImplantsKalingaNagarRouteImport.update({
    id: '/dental-implants-kalinga-nagar',
    path: '/dental-implants-kalinga-nagar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsKharavelaNagarRoute =
  DentalImplantsKharavelaNagarRouteImport.update({
    id: '/dental-implants-kharavela-nagar',
    path: '/dental-implants-kharavela-nagar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsNayapalliRoute = DentalImplantsNayapalliRouteImport.update({
  id: '/dental-implants-nayapalli',
  path: '/dental-implants-nayapalli',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsNiladriViharRoute =
  DentalImplantsNiladriViharRouteImport.update({
    id: '/dental-implants-niladri-vihar',
    path: '/dental-implants-niladri-vihar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsPatiaRoute = DentalImplantsPatiaRouteImport.update({
  id: '/dental-implants-patia',
  path: '/dental-implants-patia',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsPatrapadaRoute = DentalImplantsPatrapadaRouteImport.update({
  id: '/dental-implants-patrapada',
  path: '/dental-implants-patrapada',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsPokhariputRoute =
  DentalImplantsPokhariputRouteImport.update({
    id: '/dental-implants-pokhariput',
    path: '/dental-implants-pokhariput',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsPuriRoute = DentalImplantsPuriRouteImport.update({
  id: '/dental-implants-puri',
  path: '/dental-implants-puri',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsRourkelaRoute = DentalImplantsRourkelaRouteImport.update({
  id: '/dental-implants-rourkela',
  path: '/dental-implants-rourkela',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsSaheedNagarRoute =
  DentalImplantsSaheedNagarRouteImport.update({
    id: '/dental-implants-saheed-nagar',
    path: '/dental-implants-saheed-nagar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsSailashreeViharRoute =
  DentalImplantsSailashreeViharRouteImport.update({
    id: '/dental-implants-sailashree-vihar',
    path: '/dental-implants-sailashree-vihar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsSambalpurRoute = DentalImplantsSambalpurRouteImport.update({
  id: '/dental-implants-sambalpur',
  path: '/dental-implants-sambalpur',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsSatyaNagarRoute =
  DentalImplantsSatyaNagarRouteImport.update({
    id: '/dental-implants-satya-nagar',
    path: '/dental-implants-satya-nagar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsSundarpurRoute = DentalImplantsSundarpurRouteImport.update({
  id: '/dental-implants-sundarpur',
  path: '/dental-implants-sundarpur',
  getParentRoute: () => rootRouteImport,
} as any)
const DrSauvikSinghaRoute = DrSauvikSinghaRouteImport.update({
  id: '/dr-sauvik-singha',
  path: '/dr-sauvik-singha',
  getParentRoute: () => rootRouteImport,
} as any)
const FlaplessGuidedDentalImplantsRoute =
  FlaplessGuidedDentalImplantsRouteImport.update({
    id: '/flapless-guided-dental-implants',
    path: '/flapless-guided-dental-implants',
    getParentRoute: () => rootRouteImport,
  } as any)
const FullMouthDentalImplantsRoute = FullMouthDentalImplantsRouteImport.update({
  id: '/full-mouth-dental-implants',
  path: '/full-mouth-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmediateDentalImplantsRoute = ImmediateDentalImplantsRouteImport.update({
  id: '/immediate-dental-implants',
  path: '/immediate-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsVsBridgeVsDentureRoute =
  ImplantsVsBridgeVsDentureRouteImport.update({
    id: '/implants-vs-bridge-vs-denture',
    path: '/implants-vs-bridge-vs-denture',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultipleDentalImplantsRoute = MultipleDentalImplantsRouteImport.update({
  id: '/multiple-dental-implants',
  path: '/multiple-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleToothDentalImplantRoute =
  SingleToothDentalImplantRouteImport.update({
    id: '/single-tooth-dental-implant',
    path: '/single-tooth-dental-implant',
    getParentRoute: () => rootRouteImport,
  } as any)
const SinusLiftDentalImplantsRoute = SinusLiftDentalImplantsRouteImport.update({
  id: '/sinus-lift-dental-implants',
  path: '/sinus-lift-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ZirconiaCrownsSmileDesignRoute =
  ZirconiaCrownsSmileDesignRouteImport.update({
    id: '/zirconia-crowns-smile-design',
    path: '/zirconia-crowns-smile-design',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-on-4-all-on-6-odisha': typeof AllOn4AllOn6OdishaRoute
  '/bone-grafting-for-dental-implants': typeof BoneGraftingForDentalImplantsRoute
  '/dental-implant-cost-bhubaneswar': typeof DentalImplantCostBhubaneswarRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
  '/dental-implant-maintenance-failure': typeof DentalImplantMaintenanceFailureRoute
  '/dental-implant-second-opinion': typeof DentalImplantSecondOpinionRoute
  '/dental-implants-acharya-vihar': typeof DentalImplantsAcharyaViharRoute
  '/dental-implants-angul': typeof DentalImplantsAngulRoute
  '/dental-implants-balasore': typeof DentalImplantsBalasoreRoute
  '/dental-implants-baripada': typeof DentalImplantsBaripadaRoute
  '/dental-implants-berhampur': typeof DentalImplantsBerhampurRoute
  '/dental-implants-bhubaneswar': typeof DentalImplantsBhubaneswarRoute
  '/dental-implants-chandrasekharpur': typeof DentalImplantsChandrasekharpurRoute
  '/dental-implants-cuttack': typeof DentalImplantsCuttackRoute
  '/dental-implants-dumduma': typeof DentalImplantsDumdumaRoute
  '/dental-implants-forest-park': typeof DentalImplantsForestParkRoute
  '/dental-implants-gajapati-nagar': typeof DentalImplantsGajapatiNagarRoute
  '/dental-implants-jayadev-vihar': typeof DentalImplantsJayadevViharRoute
  '/dental-implants-jharsuguda': typeof DentalImplantsJharsugudaRoute
  '/dental-implants-kalinga-nagar': typeof DentalImplantsKalingaNagarRoute
  '/dental-implants-kharavela-nagar': typeof DentalImplantsKharavelaNagarRoute
  '/dental-implants-nayapalli': typeof DentalImplantsNayapalliRoute
  '/dental-implants-niladri-vihar': typeof DentalImplantsNiladriViharRoute
  '/dental-implants-patia': typeof DentalImplantsPatiaRoute
  '/dental-implants-patrapada': typeof DentalImplantsPatrapadaRoute
  '/dental-implants-pokhariput': typeof DentalImplantsPokhariputRoute
  '/dental-implants-puri': typeof DentalImplantsPuriRoute
  '/dental-implants-rourkela': typeof DentalImplantsRourkelaRoute
  '/dental-implants-saheed-nagar': typeof DentalImplantsSaheedNagarRoute
  '/dental-implants-sailashree-vihar': typeof DentalImplantsSailashreeViharRoute
  '/dental-implants-sambalpur': typeof DentalImplantsSambalpurRoute
  '/dental-implants-satya-nagar': typeof DentalImplantsSatyaNagarRoute
  '/dental-implants-sundarpur': typeof DentalImplantsSundarpurRoute
  '/dr-sauvik-singha': typeof DrSauvikSinghaRoute
  '/flapless-guided-dental-implants': typeof FlaplessGuidedDentalImplantsRoute
  '/full-mouth-dental-implants': typeof FullMouthDentalImplantsRoute
  '/immediate-dental-implants': typeof ImmediateDentalImplantsRoute
  '/implants-vs-bridge-vs-denture': typeof ImplantsVsBridgeVsDentureRoute
  '/multiple-dental-implants': typeof MultipleDentalImplantsRoute
  '/single-tooth-dental-implant': typeof SingleToothDentalImplantRoute
  '/sinus-lift-dental-implants': typeof SinusLiftDentalImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zirconia-crowns-smile-design': typeof ZirconiaCrownsSmileDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-on-4-all-on-6-odisha': typeof AllOn4AllOn6OdishaRoute
  '/bone-grafting-for-dental-implants': typeof BoneGraftingForDentalImplantsRoute
  '/dental-implant-cost-bhubaneswar': typeof DentalImplantCostBhubaneswarRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
  '/dental-implant-maintenance-failure': typeof DentalImplantMaintenanceFailureRoute
  '/dental-implant-second-opinion': typeof DentalImplantSecondOpinionRoute
  '/dental-implants-acharya-vihar': typeof DentalImplantsAcharyaViharRoute
  '/dental-implants-angul': typeof DentalImplantsAngulRoute
  '/dental-implants-balasore': typeof DentalImplantsBalasoreRoute
  '/dental-implants-baripada': typeof DentalImplantsBaripadaRoute
  '/dental-implants-berhampur': typeof DentalImplantsBerhampurRoute
  '/dental-implants-bhubaneswar': typeof DentalImplantsBhubaneswarRoute
  '/dental-implants-chandrasekharpur': typeof DentalImplantsChandrasekharpurRoute
  '/dental-implants-cuttack': typeof DentalImplantsCuttackRoute
  '/dental-implants-dumduma': typeof DentalImplantsDumdumaRoute
  '/dental-implants-forest-park': typeof DentalImplantsForestParkRoute
  '/dental-implants-gajapati-nagar': typeof DentalImplantsGajapatiNagarRoute
  '/dental-implants-jayadev-vihar': typeof DentalImplantsJayadevViharRoute
  '/dental-implants-jharsuguda': typeof DentalImplantsJharsugudaRoute
  '/dental-implants-kalinga-nagar': typeof DentalImplantsKalingaNagarRoute
  '/dental-implants-kharavela-nagar': typeof DentalImplantsKharavelaNagarRoute
  '/dental-implants-nayapalli': typeof DentalImplantsNayapalliRoute
  '/dental-implants-niladri-vihar': typeof DentalImplantsNiladriViharRoute
  '/dental-implants-patia': typeof DentalImplantsPatiaRoute
  '/dental-implants-patrapada': typeof DentalImplantsPatrapadaRoute
  '/dental-implants-pokhariput': typeof DentalImplantsPokhariputRoute
  '/dental-implants-puri': typeof DentalImplantsPuriRoute
  '/dental-implants-rourkela': typeof DentalImplantsRourkelaRoute
  '/dental-implants-saheed-nagar': typeof DentalImplantsSaheedNagarRoute
  '/dental-implants-sailashree-vihar': typeof DentalImplantsSailashreeViharRoute
  '/dental-implants-sambalpur': typeof DentalImplantsSambalpurRoute
  '/dental-implants-satya-nagar': typeof DentalImplantsSatyaNagarRoute
  '/dental-implants-sundarpur': typeof DentalImplantsSundarpurRoute
  '/dr-sauvik-singha': typeof DrSauvikSinghaRoute
  '/flapless-guided-dental-implants': typeof FlaplessGuidedDentalImplantsRoute
  '/full-mouth-dental-implants': typeof FullMouthDentalImplantsRoute
  '/immediate-dental-implants': typeof ImmediateDentalImplantsRoute
  '/implants-vs-bridge-vs-denture': typeof ImplantsVsBridgeVsDentureRoute
  '/multiple-dental-implants': typeof MultipleDentalImplantsRoute
  '/single-tooth-dental-implant': typeof SingleToothDentalImplantRoute
  '/sinus-lift-dental-implants': typeof SinusLiftDentalImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zirconia-crowns-smile-design': typeof ZirconiaCrownsSmileDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-on-4-all-on-6-odisha': typeof AllOn4AllOn6OdishaRoute
  '/bone-grafting-for-dental-implants': typeof BoneGraftingForDentalImplantsRoute
  '/dental-implant-cost-bhubaneswar': typeof DentalImplantCostBhubaneswarRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
  '/dental-implant-maintenance-failure': typeof DentalImplantMaintenanceFailureRoute
  '/dental-implant-second-opinion': typeof DentalImplantSecondOpinionRoute
  '/dental-implants-acharya-vihar': typeof DentalImplantsAcharyaViharRoute
  '/dental-implants-angul': typeof DentalImplantsAngulRoute
  '/dental-implants-balasore': typeof DentalImplantsBalasoreRoute
  '/dental-implants-baripada': typeof DentalImplantsBaripadaRoute
  '/dental-implants-berhampur': typeof DentalImplantsBerhampurRoute
  '/dental-implants-bhubaneswar': typeof DentalImplantsBhubaneswarRoute
  '/dental-implants-chandrasekharpur': typeof DentalImplantsChandrasekharpurRoute
  '/dental-implants-cuttack': typeof DentalImplantsCuttackRoute
  '/dental-implants-dumduma': typeof DentalImplantsDumdumaRoute
  '/dental-implants-forest-park': typeof DentalImplantsForestParkRoute
  '/dental-implants-gajapati-nagar': typeof DentalImplantsGajapatiNagarRoute
  '/dental-implants-jayadev-vihar': typeof DentalImplantsJayadevViharRoute
  '/dental-implants-jharsuguda': typeof DentalImplantsJharsugudaRoute
  '/dental-implants-kalinga-nagar': typeof DentalImplantsKalingaNagarRoute
  '/dental-implants-kharavela-nagar': typeof DentalImplantsKharavelaNagarRoute
  '/dental-implants-nayapalli': typeof DentalImplantsNayapalliRoute
  '/dental-implants-niladri-vihar': typeof DentalImplantsNiladriViharRoute
  '/dental-implants-patia': typeof DentalImplantsPatiaRoute
  '/dental-implants-patrapada': typeof DentalImplantsPatrapadaRoute
  '/dental-implants-pokhariput': typeof DentalImplantsPokhariputRoute
  '/dental-implants-puri': typeof DentalImplantsPuriRoute
  '/dental-implants-rourkela': typeof DentalImplantsRourkelaRoute
  '/dental-implants-saheed-nagar': typeof DentalImplantsSaheedNagarRoute
  '/dental-implants-sailashree-vihar': typeof DentalImplantsSailashreeViharRoute
  '/dental-implants-sambalpur': typeof DentalImplantsSambalpurRoute
  '/dental-implants-satya-nagar': typeof DentalImplantsSatyaNagarRoute
  '/dental-implants-sundarpur': typeof DentalImplantsSundarpurRoute
  '/dr-sauvik-singha': typeof DrSauvikSinghaRoute
  '/flapless-guided-dental-implants': typeof FlaplessGuidedDentalImplantsRoute
  '/full-mouth-dental-implants': typeof FullMouthDentalImplantsRoute
  '/immediate-dental-implants': typeof ImmediateDentalImplantsRoute
  '/implants-vs-bridge-vs-denture': typeof ImplantsVsBridgeVsDentureRoute
  '/multiple-dental-implants': typeof MultipleDentalImplantsRoute
  '/single-tooth-dental-implant': typeof SingleToothDentalImplantRoute
  '/sinus-lift-dental-implants': typeof SinusLiftDentalImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zirconia-crowns-smile-design': typeof ZirconiaCrownsSmileDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-on-4-all-on-6-odisha'
    | '/bone-grafting-for-dental-implants'
    | '/dental-implant-cost-bhubaneswar'
    | '/dental-implant-cost-odisha'
    | '/dental-implant-maintenance-failure'
    | '/dental-implant-second-opinion'
    | '/dental-implants-acharya-vihar'
    | '/dental-implants-angul'
    | '/dental-implants-balasore'
    | '/dental-implants-baripada'
    | '/dental-implants-berhampur'
    | '/dental-implants-bhubaneswar'
    | '/dental-implants-chandrasekharpur'
    | '/dental-implants-cuttack'
    | '/dental-implants-dumduma'
    | '/dental-implants-forest-park'
    | '/dental-implants-gajapati-nagar'
    | '/dental-implants-jayadev-vihar'
    | '/dental-implants-jharsuguda'
    | '/dental-implants-kalinga-nagar'
    | '/dental-implants-kharavela-nagar'
    | '/dental-implants-nayapalli'
    | '/dental-implants-niladri-vihar'
    | '/dental-implants-patia'
    | '/dental-implants-patrapada'
    | '/dental-implants-pokhariput'
    | '/dental-implants-puri'
    | '/dental-implants-rourkela'
    | '/dental-implants-saheed-nagar'
    | '/dental-implants-sailashree-vihar'
    | '/dental-implants-sambalpur'
    | '/dental-implants-satya-nagar'
    | '/dental-implants-sundarpur'
    | '/dr-sauvik-singha'
    | '/flapless-guided-dental-implants'
    | '/full-mouth-dental-implants'
    | '/immediate-dental-implants'
    | '/implants-vs-bridge-vs-denture'
    | '/multiple-dental-implants'
    | '/single-tooth-dental-implant'
    | '/sinus-lift-dental-implants'
    | '/sitemap.xml'
    | '/zirconia-crowns-smile-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-on-4-all-on-6-odisha'
    | '/bone-grafting-for-dental-implants'
    | '/dental-implant-cost-bhubaneswar'
    | '/dental-implant-cost-odisha'
    | '/dental-implant-maintenance-failure'
    | '/dental-implant-second-opinion'
    | '/dental-implants-acharya-vihar'
    | '/dental-implants-angul'
    | '/dental-implants-balasore'
    | '/dental-implants-baripada'
    | '/dental-implants-berhampur'
    | '/dental-implants-bhubaneswar'
    | '/dental-implants-chandrasekharpur'
    | '/dental-implants-cuttack'
    | '/dental-implants-dumduma'
    | '/dental-implants-forest-park'
    | '/dental-implants-gajapati-nagar'
    | '/dental-implants-jayadev-vihar'
    | '/dental-implants-jharsuguda'
    | '/dental-implants-kalinga-nagar'
    | '/dental-implants-kharavela-nagar'
    | '/dental-implants-nayapalli'
    | '/dental-implants-niladri-vihar'
    | '/dental-implants-patia'
    | '/dental-implants-patrapada'
    | '/dental-implants-pokhariput'
    | '/dental-implants-puri'
    | '/dental-implants-rourkela'
    | '/dental-implants-saheed-nagar'
    | '/dental-implants-sailashree-vihar'
    | '/dental-implants-sambalpur'
    | '/dental-implants-satya-nagar'
    | '/dental-implants-sundarpur'
    | '/dr-sauvik-singha'
    | '/flapless-guided-dental-implants'
    | '/full-mouth-dental-implants'
    | '/immediate-dental-implants'
    | '/implants-vs-bridge-vs-denture'
    | '/multiple-dental-implants'
    | '/single-tooth-dental-implant'
    | '/sinus-lift-dental-implants'
    | '/sitemap.xml'
    | '/zirconia-crowns-smile-design'
  id:
    | '__root__'
    | '/'
    | '/all-on-4-all-on-6-odisha'
    | '/bone-grafting-for-dental-implants'
    | '/dental-implant-cost-bhubaneswar'
    | '/dental-implant-cost-odisha'
    | '/dental-implant-maintenance-failure'
    | '/dental-implant-second-opinion'
    | '/dental-implants-acharya-vihar'
    | '/dental-implants-angul'
    | '/dental-implants-balasore'
    | '/dental-implants-baripada'
    | '/dental-implants-berhampur'
    | '/dental-implants-bhubaneswar'
    | '/dental-implants-chandrasekharpur'
    | '/dental-implants-cuttack'
    | '/dental-implants-dumduma'
    | '/dental-implants-forest-park'
    | '/dental-implants-gajapati-nagar'
    | '/dental-implants-jayadev-vihar'
    | '/dental-implants-jharsuguda'
    | '/dental-implants-kalinga-nagar'
    | '/dental-implants-kharavela-nagar'
    | '/dental-implants-nayapalli'
    | '/dental-implants-niladri-vihar'
    | '/dental-implants-patia'
    | '/dental-implants-patrapada'
    | '/dental-implants-pokhariput'
    | '/dental-implants-puri'
    | '/dental-implants-rourkela'
    | '/dental-implants-saheed-nagar'
    | '/dental-implants-sailashree-vihar'
    | '/dental-implants-sambalpur'
    | '/dental-implants-satya-nagar'
    | '/dental-implants-sundarpur'
    | '/dr-sauvik-singha'
    | '/flapless-guided-dental-implants'
    | '/full-mouth-dental-implants'
    | '/immediate-dental-implants'
    | '/implants-vs-bridge-vs-denture'
    | '/multiple-dental-implants'
    | '/single-tooth-dental-implant'
    | '/sinus-lift-dental-implants'
    | '/sitemap.xml'
    | '/zirconia-crowns-smile-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllOn4AllOn6OdishaRoute: typeof AllOn4AllOn6OdishaRoute
  BoneGraftingForDentalImplantsRoute: typeof BoneGraftingForDentalImplantsRoute
  DentalImplantCostBhubaneswarRoute: typeof DentalImplantCostBhubaneswarRoute
  DentalImplantCostOdishaRoute: typeof DentalImplantCostOdishaRoute
  DentalImplantMaintenanceFailureRoute: typeof DentalImplantMaintenanceFailureRoute
  DentalImplantSecondOpinionRoute: typeof DentalImplantSecondOpinionRoute
  DentalImplantsAcharyaViharRoute: typeof DentalImplantsAcharyaViharRoute
  DentalImplantsAngulRoute: typeof DentalImplantsAngulRoute
  DentalImplantsBalasoreRoute: typeof DentalImplantsBalasoreRoute
  DentalImplantsBaripadaRoute: typeof DentalImplantsBaripadaRoute
  DentalImplantsBerhampurRoute: typeof DentalImplantsBerhampurRoute
  DentalImplantsBhubaneswarRoute: typeof DentalImplantsBhubaneswarRoute
  DentalImplantsChandrasekharpurRoute: typeof DentalImplantsChandrasekharpurRoute
  DentalImplantsCuttackRoute: typeof DentalImplantsCuttackRoute
  DentalImplantsDumdumaRoute: typeof DentalImplantsDumdumaRoute
  DentalImplantsForestParkRoute: typeof DentalImplantsForestParkRoute
  DentalImplantsGajapatiNagarRoute: typeof DentalImplantsGajapatiNagarRoute
  DentalImplantsJayadevViharRoute: typeof DentalImplantsJayadevViharRoute
  DentalImplantsJharsugudaRoute: typeof DentalImplantsJharsugudaRoute
  DentalImplantsKalingaNagarRoute: typeof DentalImplantsKalingaNagarRoute
  DentalImplantsKharavelaNagarRoute: typeof DentalImplantsKharavelaNagarRoute
  DentalImplantsNayapalliRoute: typeof DentalImplantsNayapalliRoute
  DentalImplantsNiladriViharRoute: typeof DentalImplantsNiladriViharRoute
  DentalImplantsPatiaRoute: typeof DentalImplantsPatiaRoute
  DentalImplantsPatrapadaRoute: typeof DentalImplantsPatrapadaRoute
  DentalImplantsPokhariputRoute: typeof DentalImplantsPokhariputRoute
  DentalImplantsPuriRoute: typeof DentalImplantsPuriRoute
  DentalImplantsRourkelaRoute: typeof DentalImplantsRourkelaRoute
  DentalImplantsSaheedNagarRoute: typeof DentalImplantsSaheedNagarRoute
  DentalImplantsSailashreeViharRoute: typeof DentalImplantsSailashreeViharRoute
  DentalImplantsSambalpurRoute: typeof DentalImplantsSambalpurRoute
  DentalImplantsSatyaNagarRoute: typeof DentalImplantsSatyaNagarRoute
  DentalImplantsSundarpurRoute: typeof DentalImplantsSundarpurRoute
  DrSauvikSinghaRoute: typeof DrSauvikSinghaRoute
  FlaplessGuidedDentalImplantsRoute: typeof FlaplessGuidedDentalImplantsRoute
  FullMouthDentalImplantsRoute: typeof FullMouthDentalImplantsRoute
  ImmediateDentalImplantsRoute: typeof ImmediateDentalImplantsRoute
  ImplantsVsBridgeVsDentureRoute: typeof ImplantsVsBridgeVsDentureRoute
  MultipleDentalImplantsRoute: typeof MultipleDentalImplantsRoute
  SingleToothDentalImplantRoute: typeof SingleToothDentalImplantRoute
  SinusLiftDentalImplantsRoute: typeof SinusLiftDentalImplantsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZirconiaCrownsSmileDesignRoute: typeof ZirconiaCrownsSmileDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-on-4-all-on-6-odisha': {
      id: '/all-on-4-all-on-6-odisha'
      path: '/all-on-4-all-on-6-odisha'
      fullPath: '/all-on-4-all-on-6-odisha'
      preLoaderRoute: typeof AllOn4AllOn6OdishaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bone-grafting-for-dental-implants': {
      id: '/bone-grafting-for-dental-implants'
      path: '/bone-grafting-for-dental-implants'
      fullPath: '/bone-grafting-for-dental-implants'
      preLoaderRoute: typeof BoneGraftingForDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-cost-bhubaneswar': {
      id: '/dental-implant-cost-bhubaneswar'
      path: '/dental-implant-cost-bhubaneswar'
      fullPath: '/dental-implant-cost-bhubaneswar'
      preLoaderRoute: typeof DentalImplantCostBhubaneswarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-cost-odisha': {
      id: '/dental-implant-cost-odisha'
      path: '/dental-implant-cost-odisha'
      fullPath: '/dental-implant-cost-odisha'
      preLoaderRoute: typeof DentalImplantCostOdishaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-maintenance-failure': {
      id: '/dental-implant-maintenance-failure'
      path: '/dental-implant-maintenance-failure'
      fullPath: '/dental-implant-maintenance-failure'
      preLoaderRoute: typeof DentalImplantMaintenanceFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-second-opinion': {
      id: '/dental-implant-second-opinion'
      path: '/dental-implant-second-opinion'
      fullPath: '/dental-implant-second-opinion'
      preLoaderRoute: typeof DentalImplantSecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-acharya-vihar': {
      id: '/dental-implants-acharya-vihar'
      path: '/dental-implants-acharya-vihar'
      fullPath: '/dental-implants-acharya-vihar'
      preLoaderRoute: typeof DentalImplantsAcharyaViharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-angul': {
      id: '/dental-implants-angul'
      path: '/dental-implants-angul'
      fullPath: '/dental-implants-angul'
      preLoaderRoute: typeof DentalImplantsAngulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-balasore': {
      id: '/dental-implants-balasore'
      path: '/dental-implants-balasore'
      fullPath: '/dental-implants-balasore'
      preLoaderRoute: typeof DentalImplantsBalasoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-baripada': {
      id: '/dental-implants-baripada'
      path: '/dental-implants-baripada'
      fullPath: '/dental-implants-baripada'
      preLoaderRoute: typeof DentalImplantsBaripadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-berhampur': {
      id: '/dental-implants-berhampur'
      path: '/dental-implants-berhampur'
      fullPath: '/dental-implants-berhampur'
      preLoaderRoute: typeof DentalImplantsBerhampurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-bhubaneswar': {
      id: '/dental-implants-bhubaneswar'
      path: '/dental-implants-bhubaneswar'
      fullPath: '/dental-implants-bhubaneswar'
      preLoaderRoute: typeof DentalImplantsBhubaneswarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-chandrasekharpur': {
      id: '/dental-implants-chandrasekharpur'
      path: '/dental-implants-chandrasekharpur'
      fullPath: '/dental-implants-chandrasekharpur'
      preLoaderRoute: typeof DentalImplantsChandrasekharpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-cuttack': {
      id: '/dental-implants-cuttack'
      path: '/dental-implants-cuttack'
      fullPath: '/dental-implants-cuttack'
      preLoaderRoute: typeof DentalImplantsCuttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-dumduma': {
      id: '/dental-implants-dumduma'
      path: '/dental-implants-dumduma'
      fullPath: '/dental-implants-dumduma'
      preLoaderRoute: typeof DentalImplantsDumdumaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-forest-park': {
      id: '/dental-implants-forest-park'
      path: '/dental-implants-forest-park'
      fullPath: '/dental-implants-forest-park'
      preLoaderRoute: typeof DentalImplantsForestParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-gajapati-nagar': {
      id: '/dental-implants-gajapati-nagar'
      path: '/dental-implants-gajapati-nagar'
      fullPath: '/dental-implants-gajapati-nagar'
      preLoaderRoute: typeof DentalImplantsGajapatiNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-jayadev-vihar': {
      id: '/dental-implants-jayadev-vihar'
      path: '/dental-implants-jayadev-vihar'
      fullPath: '/dental-implants-jayadev-vihar'
      preLoaderRoute: typeof DentalImplantsJayadevViharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-jharsuguda': {
      id: '/dental-implants-jharsuguda'
      path: '/dental-implants-jharsuguda'
      fullPath: '/dental-implants-jharsuguda'
      preLoaderRoute: typeof DentalImplantsJharsugudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-kalinga-nagar': {
      id: '/dental-implants-kalinga-nagar'
      path: '/dental-implants-kalinga-nagar'
      fullPath: '/dental-implants-kalinga-nagar'
      preLoaderRoute: typeof DentalImplantsKalingaNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-kharavela-nagar': {
      id: '/dental-implants-kharavela-nagar'
      path: '/dental-implants-kharavela-nagar'
      fullPath: '/dental-implants-kharavela-nagar'
      preLoaderRoute: typeof DentalImplantsKharavelaNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-nayapalli': {
      id: '/dental-implants-nayapalli'
      path: '/dental-implants-nayapalli'
      fullPath: '/dental-implants-nayapalli'
      preLoaderRoute: typeof DentalImplantsNayapalliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-niladri-vihar': {
      id: '/dental-implants-niladri-vihar'
      path: '/dental-implants-niladri-vihar'
      fullPath: '/dental-implants-niladri-vihar'
      preLoaderRoute: typeof DentalImplantsNiladriViharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-patia': {
      id: '/dental-implants-patia'
      path: '/dental-implants-patia'
      fullPath: '/dental-implants-patia'
      preLoaderRoute: typeof DentalImplantsPatiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-patrapada': {
      id: '/dental-implants-patrapada'
      path: '/dental-implants-patrapada'
      fullPath: '/dental-implants-patrapada'
      preLoaderRoute: typeof DentalImplantsPatrapadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-pokhariput': {
      id: '/dental-implants-pokhariput'
      path: '/dental-implants-pokhariput'
      fullPath: '/dental-implants-pokhariput'
      preLoaderRoute: typeof DentalImplantsPokhariputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-puri': {
      id: '/dental-implants-puri'
      path: '/dental-implants-puri'
      fullPath: '/dental-implants-puri'
      preLoaderRoute: typeof DentalImplantsPuriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-rourkela': {
      id: '/dental-implants-rourkela'
      path: '/dental-implants-rourkela'
      fullPath: '/dental-implants-rourkela'
      preLoaderRoute: typeof DentalImplantsRourkelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-saheed-nagar': {
      id: '/dental-implants-saheed-nagar'
      path: '/dental-implants-saheed-nagar'
      fullPath: '/dental-implants-saheed-nagar'
      preLoaderRoute: typeof DentalImplantsSaheedNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-sailashree-vihar': {
      id: '/dental-implants-sailashree-vihar'
      path: '/dental-implants-sailashree-vihar'
      fullPath: '/dental-implants-sailashree-vihar'
      preLoaderRoute: typeof DentalImplantsSailashreeViharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-sambalpur': {
      id: '/dental-implants-sambalpur'
      path: '/dental-implants-sambalpur'
      fullPath: '/dental-implants-sambalpur'
      preLoaderRoute: typeof DentalImplantsSambalpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-satya-nagar': {
      id: '/dental-implants-satya-nagar'
      path: '/dental-implants-satya-nagar'
      fullPath: '/dental-implants-satya-nagar'
      preLoaderRoute: typeof DentalImplantsSatyaNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-sundarpur': {
      id: '/dental-implants-sundarpur'
      path: '/dental-implants-sundarpur'
      fullPath: '/dental-implants-sundarpur'
      preLoaderRoute: typeof DentalImplantsSundarpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dr-sauvik-singha': {
      id: '/dr-sauvik-singha'
      path: '/dr-sauvik-singha'
      fullPath: '/dr-sauvik-singha'
      preLoaderRoute: typeof DrSauvikSinghaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flapless-guided-dental-implants': {
      id: '/flapless-guided-dental-implants'
      path: '/flapless-guided-dental-implants'
      fullPath: '/flapless-guided-dental-implants'
      preLoaderRoute: typeof FlaplessGuidedDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-mouth-dental-implants': {
      id: '/full-mouth-dental-implants'
      path: '/full-mouth-dental-implants'
      fullPath: '/full-mouth-dental-implants'
      preLoaderRoute: typeof FullMouthDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immediate-dental-implants': {
      id: '/immediate-dental-implants'
      path: '/immediate-dental-implants'
      fullPath: '/immediate-dental-implants'
      preLoaderRoute: typeof ImmediateDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants-vs-bridge-vs-denture': {
      id: '/implants-vs-bridge-vs-denture'
      path: '/implants-vs-bridge-vs-denture'
      fullPath: '/implants-vs-bridge-vs-denture'
      preLoaderRoute: typeof ImplantsVsBridgeVsDentureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiple-dental-implants': {
      id: '/multiple-dental-implants'
      path: '/multiple-dental-implants'
      fullPath: '/multiple-dental-implants'
      preLoaderRoute: typeof MultipleDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-tooth-dental-implant': {
      id: '/single-tooth-dental-implant'
      path: '/single-tooth-dental-implant'
      fullPath: '/single-tooth-dental-implant'
      preLoaderRoute: typeof SingleToothDentalImplantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinus-lift-dental-implants': {
      id: '/sinus-lift-dental-implants'
      path: '/sinus-lift-dental-implants'
      fullPath: '/sinus-lift-dental-implants'
      preLoaderRoute: typeof SinusLiftDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zirconia-crowns-smile-design': {
      id: '/zirconia-crowns-smile-design'
      path: '/zirconia-crowns-smile-design'
      fullPath: '/zirconia-crowns-smile-design'
      preLoaderRoute: typeof ZirconiaCrownsSmileDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllOn4AllOn6OdishaRoute: AllOn4AllOn6OdishaRoute,
  BoneGraftingForDentalImplantsRoute: BoneGraftingForDentalImplantsRoute,
  DentalImplantCostBhubaneswarRoute: DentalImplantCostBhubaneswarRoute,
  DentalImplantCostOdishaRoute: DentalImplantCostOdishaRoute,
  DentalImplantMaintenanceFailureRoute: DentalImplantMaintenanceFailureRoute,
  DentalImplantSecondOpinionRoute: DentalImplantSecondOpinionRoute,
  DentalImplantsAcharyaViharRoute: DentalImplantsAcharyaViharRoute,
  DentalImplantsAngulRoute: DentalImplantsAngulRoute,
  DentalImplantsBalasoreRoute: DentalImplantsBalasoreRoute,
  DentalImplantsBaripadaRoute: DentalImplantsBaripadaRoute,
  DentalImplantsBerhampurRoute: DentalImplantsBerhampurRoute,
  DentalImplantsBhubaneswarRoute: DentalImplantsBhubaneswarRoute,
  DentalImplantsChandrasekharpurRoute: DentalImplantsChandrasekharpurRoute,
  DentalImplantsCuttackRoute: DentalImplantsCuttackRoute,
  DentalImplantsDumdumaRoute: DentalImplantsDumdumaRoute,
  DentalImplantsForestParkRoute: DentalImplantsForestParkRoute,
  DentalImplantsGajapatiNagarRoute: DentalImplantsGajapatiNagarRoute,
  DentalImplantsJayadevViharRoute: DentalImplantsJayadevViharRoute,
  DentalImplantsJharsugudaRoute: DentalImplantsJharsugudaRoute,
  DentalImplantsKalingaNagarRoute: DentalImplantsKalingaNagarRoute,
  DentalImplantsKharavelaNagarRoute: DentalImplantsKharavelaNagarRoute,
  DentalImplantsNayapalliRoute: DentalImplantsNayapalliRoute,
  DentalImplantsNiladriViharRoute: DentalImplantsNiladriViharRoute,
  DentalImplantsPatiaRoute: DentalImplantsPatiaRoute,
  DentalImplantsPatrapadaRoute: DentalImplantsPatrapadaRoute,
  DentalImplantsPokhariputRoute: DentalImplantsPokhariputRoute,
  DentalImplantsPuriRoute: DentalImplantsPuriRoute,
  DentalImplantsRourkelaRoute: DentalImplantsRourkelaRoute,
  DentalImplantsSaheedNagarRoute: DentalImplantsSaheedNagarRoute,
  DentalImplantsSailashreeViharRoute: DentalImplantsSailashreeViharRoute,
  DentalImplantsSambalpurRoute: DentalImplantsSambalpurRoute,
  DentalImplantsSatyaNagarRoute: DentalImplantsSatyaNagarRoute,
  DentalImplantsSundarpurRoute: DentalImplantsSundarpurRoute,
  DrSauvikSinghaRoute: DrSauvikSinghaRoute,
  FlaplessGuidedDentalImplantsRoute: FlaplessGuidedDentalImplantsRoute,
  FullMouthDentalImplantsRoute: FullMouthDentalImplantsRoute,
  ImmediateDentalImplantsRoute: ImmediateDentalImplantsRoute,
  ImplantsVsBridgeVsDentureRoute: ImplantsVsBridgeVsDentureRoute,
  MultipleDentalImplantsRoute: MultipleDentalImplantsRoute,
  SingleToothDentalImplantRoute: SingleToothDentalImplantRoute,
  SinusLiftDentalImplantsRoute: SinusLiftDentalImplantsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZirconiaCrownsSmileDesignRoute: ZirconiaCrownsSmileDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
