/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DentalImplantCostOdishaRouteImport } from './routes/dental-implant-cost-odisha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantCostOdishaRoute = DentalImplantCostOdishaRouteImport.update({
  id: '/dental-implant-cost-odisha',
  path: '/dental-implant-cost-odisha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dental-implant-cost-odisha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dental-implant-cost-odisha'
  id: '__root__' | '/' | '/dental-implant-cost-odisha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DentalImplantCostOdishaRoute: typeof DentalImplantCostOdishaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-cost-odisha': {
      id: '/dental-implant-cost-odisha'
      path: '/dental-implant-cost-odisha'
      fullPath: '/dental-implant-cost-odisha'
      preLoaderRoute: typeof DentalImplantCostOdishaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DentalImplantCostOdishaRoute: DentalImplantCostOdishaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
