/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllOn4AllOn6OdishaRouteImport } from './routes/all-on-4-all-on-6-odisha'
import { Route as BoneGraftingForDentalImplantsRouteImport } from './routes/bone-grafting-for-dental-implants'
import { Route as DentalImplantCostBhubaneswarRouteImport } from './routes/dental-implant-cost-bhubaneswar'
import { Route as DentalImplantCostOdishaRouteImport } from './routes/dental-implant-cost-odisha'
import { Route as DentalImplantMaintenanceFailureRouteImport } from './routes/dental-implant-maintenance-failure'
import { Route as DentalImplantSecondOpinionRouteImport } from './routes/dental-implant-second-opinion'
import { Route as DentalImplantsAngulRouteImport } from './routes/dental-implants-angul'
import { Route as DentalImplantsBalasoreRouteImport } from './routes/dental-implants-balasore'
import { Route as DentalImplantsBaripadaRouteImport } from './routes/dental-implants-baripada'
import { Route as DentalImplantsBerhampurRouteImport } from './routes/dental-implants-berhampur'
import { Route as DentalImplantsBhubaneswarRouteImport } from './routes/dental-implants-bhubaneswar'
import { Route as DentalImplantsCuttackRouteImport } from './routes/dental-implants-cuttack'
import { Route as DentalImplantsJharsugudaRouteImport } from './routes/dental-implants-jharsuguda'
import { Route as DentalImplantsPuriRouteImport } from './routes/dental-implants-puri'
import { Route as DentalImplantsRourkelaRouteImport } from './routes/dental-implants-rourkela'
import { Route as DentalImplantsSambalpurRouteImport } from './routes/dental-implants-sambalpur'
import { Route as FlaplessGuidedDentalImplantsRouteImport } from './routes/flapless-guided-dental-implants'
import { Route as FullMouthDentalImplantsRouteImport } from './routes/full-mouth-dental-implants'
import { Route as ImmediateDentalImplantsRouteImport } from './routes/immediate-dental-implants'
import { Route as ImplantsVsBridgeVsDentureRouteImport } from './routes/implants-vs-bridge-vs-denture'
import { Route as MultipleDentalImplantsRouteImport } from './routes/multiple-dental-implants'
import { Route as SingleToothDentalImplantRouteImport } from './routes/single-tooth-dental-implant'
import { Route as SinusLiftDentalImplantsRouteImport } from './routes/sinus-lift-dental-implants'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ZirconiaCrownsSmileDesignRouteImport } from './routes/zirconia-crowns-smile-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllOn4AllOn6OdishaRoute = AllOn4AllOn6OdishaRouteImport.update({
  id: '/all-on-4-all-on-6-odisha',
  path: '/all-on-4-all-on-6-odisha',
  getParentRoute: () => rootRouteImport,
} as any)
const BoneGraftingForDentalImplantsRoute =
  BoneGraftingForDentalImplantsRouteImport.update({
    id: '/bone-grafting-for-dental-implants',
    path: '/bone-grafting-for-dental-implants',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantCostBhubaneswarRoute =
  DentalImplantCostBhubaneswarRouteImport.update({
    id: '/dental-implant-cost-bhubaneswar',
    path: '/dental-implant-cost-bhubaneswar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantCostOdishaRoute = DentalImplantCostOdishaRouteImport.update({
  id: '/dental-implant-cost-odisha',
  path: '/dental-implant-cost-odisha',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantMaintenanceFailureRoute =
  DentalImplantMaintenanceFailureRouteImport.update({
    id: '/dental-implant-maintenance-failure',
    path: '/dental-implant-maintenance-failure',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantSecondOpinionRoute =
  DentalImplantSecondOpinionRouteImport.update({
    id: '/dental-implant-second-opinion',
    path: '/dental-implant-second-opinion',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsAngulRoute = DentalImplantsAngulRouteImport.update({
  id: '/dental-implants-angul',
  path: '/dental-implants-angul',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBalasoreRoute = DentalImplantsBalasoreRouteImport.update({
  id: '/dental-implants-balasore',
  path: '/dental-implants-balasore',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBaripadaRoute = DentalImplantsBaripadaRouteImport.update({
  id: '/dental-implants-baripada',
  path: '/dental-implants-baripada',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBerhampurRoute = DentalImplantsBerhampurRouteImport.update({
  id: '/dental-implants-berhampur',
  path: '/dental-implants-berhampur',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsBhubaneswarRoute =
  DentalImplantsBhubaneswarRouteImport.update({
    id: '/dental-implants-bhubaneswar',
    path: '/dental-implants-bhubaneswar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsCuttackRoute = DentalImplantsCuttackRouteImport.update({
  id: '/dental-implants-cuttack',
  path: '/dental-implants-cuttack',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsJharsugudaRoute =
  DentalImplantsJharsugudaRouteImport.update({
    id: '/dental-implants-jharsuguda',
    path: '/dental-implants-jharsuguda',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantsPuriRoute = DentalImplantsPuriRouteImport.update({
  id: '/dental-implants-puri',
  path: '/dental-implants-puri',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsRourkelaRoute = DentalImplantsRourkelaRouteImport.update({
  id: '/dental-implants-rourkela',
  path: '/dental-implants-rourkela',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsSambalpurRoute = DentalImplantsSambalpurRouteImport.update({
  id: '/dental-implants-sambalpur',
  path: '/dental-implants-sambalpur',
  getParentRoute: () => rootRouteImport,
} as any)
const FlaplessGuidedDentalImplantsRoute =
  FlaplessGuidedDentalImplantsRouteImport.update({
    id: '/flapless-guided-dental-implants',
    path: '/flapless-guided-dental-implants',
    getParentRoute: () => rootRouteImport,
  } as any)
const FullMouthDentalImplantsRoute = FullMouthDentalImplantsRouteImport.update({
  id: '/full-mouth-dental-implants',
  path: '/full-mouth-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmediateDentalImplantsRoute = ImmediateDentalImplantsRouteImport.update({
  id: '/immediate-dental-implants',
  path: '/immediate-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsVsBridgeVsDentureRoute =
  ImplantsVsBridgeVsDentureRouteImport.update({
    id: '/implants-vs-bridge-vs-denture',
    path: '/implants-vs-bridge-vs-denture',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultipleDentalImplantsRoute = MultipleDentalImplantsRouteImport.update({
  id: '/multiple-dental-implants',
  path: '/multiple-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleToothDentalImplantRoute =
  SingleToothDentalImplantRouteImport.update({
    id: '/single-tooth-dental-implant',
    path: '/single-tooth-dental-implant',
    getParentRoute: () => rootRouteImport,
  } as any)
const SinusLiftDentalImplantsRoute = SinusLiftDentalImplantsRouteImport.update({
  id: '/sinus-lift-dental-implants',
  path: '/sinus-lift-dental-implants',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ZirconiaCrownsSmileDesignRoute =
  ZirconiaCrownsSmileDesignRouteImport.update({
    id: '/zirconia-crowns-smile-design',
    path: '/zirconia-crowns-smile-design',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-on-4-all-on-6-odisha': typeof AllOn4AllOn6OdishaRoute
  '/bone-grafting-for-dental-implants': typeof BoneGraftingForDentalImplantsRoute
  '/dental-implant-cost-bhubaneswar': typeof DentalImplantCostBhubaneswarRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
  '/dental-implant-maintenance-failure': typeof DentalImplantMaintenanceFailureRoute
  '/dental-implant-second-opinion': typeof DentalImplantSecondOpinionRoute
  '/dental-implants-angul': typeof DentalImplantsAngulRoute
  '/dental-implants-balasore': typeof DentalImplantsBalasoreRoute
  '/dental-implants-baripada': typeof DentalImplantsBaripadaRoute
  '/dental-implants-berhampur': typeof DentalImplantsBerhampurRoute
  '/dental-implants-bhubaneswar': typeof DentalImplantsBhubaneswarRoute
  '/dental-implants-cuttack': typeof DentalImplantsCuttackRoute
  '/dental-implants-jharsuguda': typeof DentalImplantsJharsugudaRoute
  '/dental-implants-puri': typeof DentalImplantsPuriRoute
  '/dental-implants-rourkela': typeof DentalImplantsRourkelaRoute
  '/dental-implants-sambalpur': typeof DentalImplantsSambalpurRoute
  '/flapless-guided-dental-implants': typeof FlaplessGuidedDentalImplantsRoute
  '/full-mouth-dental-implants': typeof FullMouthDentalImplantsRoute
  '/immediate-dental-implants': typeof ImmediateDentalImplantsRoute
  '/implants-vs-bridge-vs-denture': typeof ImplantsVsBridgeVsDentureRoute
  '/multiple-dental-implants': typeof MultipleDentalImplantsRoute
  '/single-tooth-dental-implant': typeof SingleToothDentalImplantRoute
  '/sinus-lift-dental-implants': typeof SinusLiftDentalImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zirconia-crowns-smile-design': typeof ZirconiaCrownsSmileDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-on-4-all-on-6-odisha': typeof AllOn4AllOn6OdishaRoute
  '/bone-grafting-for-dental-implants': typeof BoneGraftingForDentalImplantsRoute
  '/dental-implant-cost-bhubaneswar': typeof DentalImplantCostBhubaneswarRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
  '/dental-implant-maintenance-failure': typeof DentalImplantMaintenanceFailureRoute
  '/dental-implant-second-opinion': typeof DentalImplantSecondOpinionRoute
  '/dental-implants-angul': typeof DentalImplantsAngulRoute
  '/dental-implants-balasore': typeof DentalImplantsBalasoreRoute
  '/dental-implants-baripada': typeof DentalImplantsBaripadaRoute
  '/dental-implants-berhampur': typeof DentalImplantsBerhampurRoute
  '/dental-implants-bhubaneswar': typeof DentalImplantsBhubaneswarRoute
  '/dental-implants-cuttack': typeof DentalImplantsCuttackRoute
  '/dental-implants-jharsuguda': typeof DentalImplantsJharsugudaRoute
  '/dental-implants-puri': typeof DentalImplantsPuriRoute
  '/dental-implants-rourkela': typeof DentalImplantsRourkelaRoute
  '/dental-implants-sambalpur': typeof DentalImplantsSambalpurRoute
  '/flapless-guided-dental-implants': typeof FlaplessGuidedDentalImplantsRoute
  '/full-mouth-dental-implants': typeof FullMouthDentalImplantsRoute
  '/immediate-dental-implants': typeof ImmediateDentalImplantsRoute
  '/implants-vs-bridge-vs-denture': typeof ImplantsVsBridgeVsDentureRoute
  '/multiple-dental-implants': typeof MultipleDentalImplantsRoute
  '/single-tooth-dental-implant': typeof SingleToothDentalImplantRoute
  '/sinus-lift-dental-implants': typeof SinusLiftDentalImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zirconia-crowns-smile-design': typeof ZirconiaCrownsSmileDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-on-4-all-on-6-odisha': typeof AllOn4AllOn6OdishaRoute
  '/bone-grafting-for-dental-implants': typeof BoneGraftingForDentalImplantsRoute
  '/dental-implant-cost-bhubaneswar': typeof DentalImplantCostBhubaneswarRoute
  '/dental-implant-cost-odisha': typeof DentalImplantCostOdishaRoute
  '/dental-implant-maintenance-failure': typeof DentalImplantMaintenanceFailureRoute
  '/dental-implant-second-opinion': typeof DentalImplantSecondOpinionRoute
  '/dental-implants-angul': typeof DentalImplantsAngulRoute
  '/dental-implants-balasore': typeof DentalImplantsBalasoreRoute
  '/dental-implants-baripada': typeof DentalImplantsBaripadaRoute
  '/dental-implants-berhampur': typeof DentalImplantsBerhampurRoute
  '/dental-implants-bhubaneswar': typeof DentalImplantsBhubaneswarRoute
  '/dental-implants-cuttack': typeof DentalImplantsCuttackRoute
  '/dental-implants-jharsuguda': typeof DentalImplantsJharsugudaRoute
  '/dental-implants-puri': typeof DentalImplantsPuriRoute
  '/dental-implants-rourkela': typeof DentalImplantsRourkelaRoute
  '/dental-implants-sambalpur': typeof DentalImplantsSambalpurRoute
  '/flapless-guided-dental-implants': typeof FlaplessGuidedDentalImplantsRoute
  '/full-mouth-dental-implants': typeof FullMouthDentalImplantsRoute
  '/immediate-dental-implants': typeof ImmediateDentalImplantsRoute
  '/implants-vs-bridge-vs-denture': typeof ImplantsVsBridgeVsDentureRoute
  '/multiple-dental-implants': typeof MultipleDentalImplantsRoute
  '/single-tooth-dental-implant': typeof SingleToothDentalImplantRoute
  '/sinus-lift-dental-implants': typeof SinusLiftDentalImplantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zirconia-crowns-smile-design': typeof ZirconiaCrownsSmileDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-on-4-all-on-6-odisha'
    | '/bone-grafting-for-dental-implants'
    | '/dental-implant-cost-bhubaneswar'
    | '/dental-implant-cost-odisha'
    | '/dental-implant-maintenance-failure'
    | '/dental-implant-second-opinion'
    | '/dental-implants-angul'
    | '/dental-implants-balasore'
    | '/dental-implants-baripada'
    | '/dental-implants-berhampur'
    | '/dental-implants-bhubaneswar'
    | '/dental-implants-cuttack'
    | '/dental-implants-jharsuguda'
    | '/dental-implants-puri'
    | '/dental-implants-rourkela'
    | '/dental-implants-sambalpur'
    | '/flapless-guided-dental-implants'
    | '/full-mouth-dental-implants'
    | '/immediate-dental-implants'
    | '/implants-vs-bridge-vs-denture'
    | '/multiple-dental-implants'
    | '/single-tooth-dental-implant'
    | '/sinus-lift-dental-implants'
    | '/sitemap.xml'
    | '/zirconia-crowns-smile-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-on-4-all-on-6-odisha'
    | '/bone-grafting-for-dental-implants'
    | '/dental-implant-cost-bhubaneswar'
    | '/dental-implant-cost-odisha'
    | '/dental-implant-maintenance-failure'
    | '/dental-implant-second-opinion'
    | '/dental-implants-angul'
    | '/dental-implants-balasore'
    | '/dental-implants-baripada'
    | '/dental-implants-berhampur'
    | '/dental-implants-bhubaneswar'
    | '/dental-implants-cuttack'
    | '/dental-implants-jharsuguda'
    | '/dental-implants-puri'
    | '/dental-implants-rourkela'
    | '/dental-implants-sambalpur'
    | '/flapless-guided-dental-implants'
    | '/full-mouth-dental-implants'
    | '/immediate-dental-implants'
    | '/implants-vs-bridge-vs-denture'
    | '/multiple-dental-implants'
    | '/single-tooth-dental-implant'
    | '/sinus-lift-dental-implants'
    | '/sitemap.xml'
    | '/zirconia-crowns-smile-design'
  id:
    | '__root__'
    | '/'
    | '/all-on-4-all-on-6-odisha'
    | '/bone-grafting-for-dental-implants'
    | '/dental-implant-cost-bhubaneswar'
    | '/dental-implant-cost-odisha'
    | '/dental-implant-maintenance-failure'
    | '/dental-implant-second-opinion'
    | '/dental-implants-angul'
    | '/dental-implants-balasore'
    | '/dental-implants-baripada'
    | '/dental-implants-berhampur'
    | '/dental-implants-bhubaneswar'
    | '/dental-implants-cuttack'
    | '/dental-implants-jharsuguda'
    | '/dental-implants-puri'
    | '/dental-implants-rourkela'
    | '/dental-implants-sambalpur'
    | '/flapless-guided-dental-implants'
    | '/full-mouth-dental-implants'
    | '/immediate-dental-implants'
    | '/implants-vs-bridge-vs-denture'
    | '/multiple-dental-implants'
    | '/single-tooth-dental-implant'
    | '/sinus-lift-dental-implants'
    | '/sitemap.xml'
    | '/zirconia-crowns-smile-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllOn4AllOn6OdishaRoute: typeof AllOn4AllOn6OdishaRoute
  BoneGraftingForDentalImplantsRoute: typeof BoneGraftingForDentalImplantsRoute
  DentalImplantCostBhubaneswarRoute: typeof DentalImplantCostBhubaneswarRoute
  DentalImplantCostOdishaRoute: typeof DentalImplantCostOdishaRoute
  DentalImplantMaintenanceFailureRoute: typeof DentalImplantMaintenanceFailureRoute
  DentalImplantSecondOpinionRoute: typeof DentalImplantSecondOpinionRoute
  DentalImplantsAngulRoute: typeof DentalImplantsAngulRoute
  DentalImplantsBalasoreRoute: typeof DentalImplantsBalasoreRoute
  DentalImplantsBaripadaRoute: typeof DentalImplantsBaripadaRoute
  DentalImplantsBerhampurRoute: typeof DentalImplantsBerhampurRoute
  DentalImplantsBhubaneswarRoute: typeof DentalImplantsBhubaneswarRoute
  DentalImplantsCuttackRoute: typeof DentalImplantsCuttackRoute
  DentalImplantsJharsugudaRoute: typeof DentalImplantsJharsugudaRoute
  DentalImplantsPuriRoute: typeof DentalImplantsPuriRoute
  DentalImplantsRourkelaRoute: typeof DentalImplantsRourkelaRoute
  DentalImplantsSambalpurRoute: typeof DentalImplantsSambalpurRoute
  FlaplessGuidedDentalImplantsRoute: typeof FlaplessGuidedDentalImplantsRoute
  FullMouthDentalImplantsRoute: typeof FullMouthDentalImplantsRoute
  ImmediateDentalImplantsRoute: typeof ImmediateDentalImplantsRoute
  ImplantsVsBridgeVsDentureRoute: typeof ImplantsVsBridgeVsDentureRoute
  MultipleDentalImplantsRoute: typeof MultipleDentalImplantsRoute
  SingleToothDentalImplantRoute: typeof SingleToothDentalImplantRoute
  SinusLiftDentalImplantsRoute: typeof SinusLiftDentalImplantsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZirconiaCrownsSmileDesignRoute: typeof ZirconiaCrownsSmileDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-on-4-all-on-6-odisha': {
      id: '/all-on-4-all-on-6-odisha'
      path: '/all-on-4-all-on-6-odisha'
      fullPath: '/all-on-4-all-on-6-odisha'
      preLoaderRoute: typeof AllOn4AllOn6OdishaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bone-grafting-for-dental-implants': {
      id: '/bone-grafting-for-dental-implants'
      path: '/bone-grafting-for-dental-implants'
      fullPath: '/bone-grafting-for-dental-implants'
      preLoaderRoute: typeof BoneGraftingForDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-cost-bhubaneswar': {
      id: '/dental-implant-cost-bhubaneswar'
      path: '/dental-implant-cost-bhubaneswar'
      fullPath: '/dental-implant-cost-bhubaneswar'
      preLoaderRoute: typeof DentalImplantCostBhubaneswarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-cost-odisha': {
      id: '/dental-implant-cost-odisha'
      path: '/dental-implant-cost-odisha'
      fullPath: '/dental-implant-cost-odisha'
      preLoaderRoute: typeof DentalImplantCostOdishaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-maintenance-failure': {
      id: '/dental-implant-maintenance-failure'
      path: '/dental-implant-maintenance-failure'
      fullPath: '/dental-implant-maintenance-failure'
      preLoaderRoute: typeof DentalImplantMaintenanceFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-second-opinion': {
      id: '/dental-implant-second-opinion'
      path: '/dental-implant-second-opinion'
      fullPath: '/dental-implant-second-opinion'
      preLoaderRoute: typeof DentalImplantSecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-angul': {
      id: '/dental-implants-angul'
      path: '/dental-implants-angul'
      fullPath: '/dental-implants-angul'
      preLoaderRoute: typeof DentalImplantsAngulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-balasore': {
      id: '/dental-implants-balasore'
      path: '/dental-implants-balasore'
      fullPath: '/dental-implants-balasore'
      preLoaderRoute: typeof DentalImplantsBalasoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-baripada': {
      id: '/dental-implants-baripada'
      path: '/dental-implants-baripada'
      fullPath: '/dental-implants-baripada'
      preLoaderRoute: typeof DentalImplantsBaripadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-berhampur': {
      id: '/dental-implants-berhampur'
      path: '/dental-implants-berhampur'
      fullPath: '/dental-implants-berhampur'
      preLoaderRoute: typeof DentalImplantsBerhampurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-bhubaneswar': {
      id: '/dental-implants-bhubaneswar'
      path: '/dental-implants-bhubaneswar'
      fullPath: '/dental-implants-bhubaneswar'
      preLoaderRoute: typeof DentalImplantsBhubaneswarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-cuttack': {
      id: '/dental-implants-cuttack'
      path: '/dental-implants-cuttack'
      fullPath: '/dental-implants-cuttack'
      preLoaderRoute: typeof DentalImplantsCuttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-jharsuguda': {
      id: '/dental-implants-jharsuguda'
      path: '/dental-implants-jharsuguda'
      fullPath: '/dental-implants-jharsuguda'
      preLoaderRoute: typeof DentalImplantsJharsugudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-puri': {
      id: '/dental-implants-puri'
      path: '/dental-implants-puri'
      fullPath: '/dental-implants-puri'
      preLoaderRoute: typeof DentalImplantsPuriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-rourkela': {
      id: '/dental-implants-rourkela'
      path: '/dental-implants-rourkela'
      fullPath: '/dental-implants-rourkela'
      preLoaderRoute: typeof DentalImplantsRourkelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-sambalpur': {
      id: '/dental-implants-sambalpur'
      path: '/dental-implants-sambalpur'
      fullPath: '/dental-implants-sambalpur'
      preLoaderRoute: typeof DentalImplantsSambalpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flapless-guided-dental-implants': {
      id: '/flapless-guided-dental-implants'
      path: '/flapless-guided-dental-implants'
      fullPath: '/flapless-guided-dental-implants'
      preLoaderRoute: typeof FlaplessGuidedDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-mouth-dental-implants': {
      id: '/full-mouth-dental-implants'
      path: '/full-mouth-dental-implants'
      fullPath: '/full-mouth-dental-implants'
      preLoaderRoute: typeof FullMouthDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immediate-dental-implants': {
      id: '/immediate-dental-implants'
      path: '/immediate-dental-implants'
      fullPath: '/immediate-dental-implants'
      preLoaderRoute: typeof ImmediateDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants-vs-bridge-vs-denture': {
      id: '/implants-vs-bridge-vs-denture'
      path: '/implants-vs-bridge-vs-denture'
      fullPath: '/implants-vs-bridge-vs-denture'
      preLoaderRoute: typeof ImplantsVsBridgeVsDentureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiple-dental-implants': {
      id: '/multiple-dental-implants'
      path: '/multiple-dental-implants'
      fullPath: '/multiple-dental-implants'
      preLoaderRoute: typeof MultipleDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-tooth-dental-implant': {
      id: '/single-tooth-dental-implant'
      path: '/single-tooth-dental-implant'
      fullPath: '/single-tooth-dental-implant'
      preLoaderRoute: typeof SingleToothDentalImplantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinus-lift-dental-implants': {
      id: '/sinus-lift-dental-implants'
      path: '/sinus-lift-dental-implants'
      fullPath: '/sinus-lift-dental-implants'
      preLoaderRoute: typeof SinusLiftDentalImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zirconia-crowns-smile-design': {
      id: '/zirconia-crowns-smile-design'
      path: '/zirconia-crowns-smile-design'
      fullPath: '/zirconia-crowns-smile-design'
      preLoaderRoute: typeof ZirconiaCrownsSmileDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllOn4AllOn6OdishaRoute: AllOn4AllOn6OdishaRoute,
  BoneGraftingForDentalImplantsRoute: BoneGraftingForDentalImplantsRoute,
  DentalImplantCostBhubaneswarRoute: DentalImplantCostBhubaneswarRoute,
  DentalImplantCostOdishaRoute: DentalImplantCostOdishaRoute,
  DentalImplantMaintenanceFailureRoute: DentalImplantMaintenanceFailureRoute,
  DentalImplantSecondOpinionRoute: DentalImplantSecondOpinionRoute,
  DentalImplantsAngulRoute: DentalImplantsAngulRoute,
  DentalImplantsBalasoreRoute: DentalImplantsBalasoreRoute,
  DentalImplantsBaripadaRoute: DentalImplantsBaripadaRoute,
  DentalImplantsBerhampurRoute: DentalImplantsBerhampurRoute,
  DentalImplantsBhubaneswarRoute: DentalImplantsBhubaneswarRoute,
  DentalImplantsCuttackRoute: DentalImplantsCuttackRoute,
  DentalImplantsJharsugudaRoute: DentalImplantsJharsugudaRoute,
  DentalImplantsPuriRoute: DentalImplantsPuriRoute,
  DentalImplantsRourkelaRoute: DentalImplantsRourkelaRoute,
  DentalImplantsSambalpurRoute: DentalImplantsSambalpurRoute,
  FlaplessGuidedDentalImplantsRoute: FlaplessGuidedDentalImplantsRoute,
  FullMouthDentalImplantsRoute: FullMouthDentalImplantsRoute,
  ImmediateDentalImplantsRoute: ImmediateDentalImplantsRoute,
  ImplantsVsBridgeVsDentureRoute: ImplantsVsBridgeVsDentureRoute,
  MultipleDentalImplantsRoute: MultipleDentalImplantsRoute,
  SingleToothDentalImplantRoute: SingleToothDentalImplantRoute,
  SinusLiftDentalImplantsRoute: SinusLiftDentalImplantsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZirconiaCrownsSmileDesignRoute: ZirconiaCrownsSmileDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
